# Generated by Django 5.2.10 on 2026-01-22 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=63)),
                ('actor_user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor_email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], db_index=True, default='success', max_length=16)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=128)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audits_audi_action_28d6c5_idx'), models.Index(fields=['actor_email', 'created_at'], name='audits_audi_actor_e_3f285b_idx'), models.Index(fields=['object_type', 'object_id'], name='audits_audi_object__148ded_idx')],
            },
        ),
    ]
