# Generated by Django 5.2.10 on 2026-01-22 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='event_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_path',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
