# Generated by Django 5.2.10 on 2026-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auditevent_event_id_auditevent_request_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
