# Generated by Django 5.2.10 on 2026-01-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
