# Generated by Django 5.2.10 on 2026-01-23 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=60)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='addresses.address')),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'created_at'], name='contacts_co_email_e61c93_idx'), models.Index(fields=['phone', 'created_at'], name='contacts_co_phone_130b90_idx')],
            },
        ),
    ]
