# Generated by Django 5.2.10 on 2026-01-22 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_domain_created_at_domain_uid_domain_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
