# Generated by Django 5.2.10 on 2026-01-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_alter_domain_uid_alter_tenant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='source',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
