# Generated by Django 5.2.10 on 2026-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_tenant_external_id_tenant_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
