# Generated by Django 5.2.10 on 2026-01-23 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed use')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='addresses.address')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(db_index=True, max_length=60)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('offline', 'Offline')], db_index=True, default='vacant', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['portfolio', 'created_at'], name='properties__portfol_35e298_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'created_at'], name='properties__propert_4d3fee_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'status'], name='properties__propert_41331e_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'unit_number'), name='properties_unit_unique_per_property'),
        ),
    ]
