# Generated by Django 5.2.10 on 2026-01-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_tags_unit_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='previous_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
