# Generated by Django 5.2.10 on 2026-01-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_previous_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
