# Generated by Django 5.2.10 on 2026-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_unit_purchase_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'created_at'], name='properties__propert_8f85f0_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status', 'created_at'], name='properties__status_eec315_idx'),
        ),
    ]
