# Generated by Django 5.2.10 on 2026-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_unitlisting_fields_and_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='managing_agent_reference',
            field=models.CharField(blank=True, help_text='Managing agent account or reference for this unit.', max_length=120),
        ),
        migrations.AddField(
            model_name='unit',
            name='municipal_reference',
            field=models.CharField(blank=True, help_text='Municipal account or reference number for this unit.', max_length=120),
        ),
    ]
