# Generated by Django 5.2.10 on 2026-06-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0001_initial'),
        ('managing_agents', '0001_initial'),
        ('properties', '0008_unit_reference_fields'),
        ('rental_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='estate_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='estate_agents.estateagent'),
        ),
        migrations.AddField(
            model_name='unit',
            name='managing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='managing_agents.managingagent'),
        ),
        migrations.AddField(
            model_name='unit',
            name='rental_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='rental_agents.rentalagent'),
        ),
    ]
