# Generated by Django 5.2.10 on 2026-06-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_unit_purchase_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingphoto',
            new_name='properties__listing_b1b8fc_idx',
            old_name='properties__listin_9865c1_idx',
        ),
        migrations.RenameIndex(
            model_name='unitlisting',
            new_name='properties__is_publ_7938cb_idx',
            old_name='properties__is_publ_6f2d7a_idx',
        ),
    ]
