# Generated by Django 5.2.10 on 2026-06-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agents', '0003_estateagent_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='estateagent',
            new_name='estate_agen_is_acti_45ecb2_idx',
            old_name='estate_agen_is_acti_name_idx',
        ),
    ]
