# Generated by Django 5.2.10 on 2026-06-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_agents', '0003_rentalagent_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rentalagent',
            new_name='rental_agen_is_acti_0a7e72_idx',
            old_name='rental_agen_is_acti_name_idx',
        ),
    ]
