# Generated by Django 5.2.10 on 2026-04-30 16:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0007_unitlisting_fields_and_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.unit')),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
                'indexes': [models.Index(fields=['unit', 'expense_date'], name='accounting__unit_id_cd91e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='properties.unit')),
            ],
            options={
                'ordering': ('-issue_date', '-created_at'),
                'indexes': [models.Index(fields=['unit', 'issue_date'], name='accounting__unit_id_79cb02_idx')],
            },
        ),
    ]
