# Generated by Django 5.2.10 on 2026-06-15 12:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_assetcapitalinvestment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetcapitalinvestment',
            new_name='accounting__related_4384b9_idx',
            old_name='accounting__related_4a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='assetcapitalinvestment',
            new_name='accounting__unit_id_319da5_idx',
            old_name='accounting__unit_id_7c2b91_idx',
        ),
        migrations.AddField(
            model_name='assetcapitalinvestment',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assetcapitalinvestment',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='assetcapitalinvestment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
