# Generated by Django 5.2.10 on 2026-01-23 12:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_day', models.PositiveSmallIntegerField(default=1)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('primary_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='contacts.contact')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'indexes': [models.Index(fields=['unit', 'status'], name='leases_leas_unit_id_d203d6_idx'), models.Index(fields=['primary_tenant', 'status'], name='leases_leas_primary_1d25e3_idx')],
            },
        ),
    ]
