# Generated by Django 5.2.10 on 2026-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
