# Generated by Django 5.2.10 on 2026-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_tags'),
        ('leases', '0002_lease_tags'),
        ('properties', '0005_unit_properties__propert_8f85f0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit', 'created_at'], name='leases_leas_unit_id_fe2e83_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['primary_tenant', 'created_at'], name='leases_leas_primary_11f016_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status', 'created_at'], name='leases_leas_status_0ad55e_idx'),
        ),
    ]
