# Generated by Django 5.2.10 on 2026-05-03 19:17

import apps.marketing.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(blank=True, max_length=120)),
                ('unit_number', models.CharField(max_length=60)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('lease_term_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('furnished', models.BooleanField(default=False)),
                ('pet_policy', models.CharField(blank=True, max_length=120)),
                ('parking_spaces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('utilities_included', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('amenities', models.CharField(blank=True, help_text='Comma-separated list', max_length=250)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['is_published', 'created_at'], name='marketing_p_is_publ_7e3aba_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to=apps.marketing.models._public_listing_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketing.publiclisting')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['listing', 'is_primary'], name='marketing_p_listing_7f3ce6_idx')],
            },
        ),
    ]
