# Generated by Django 5.2.10 on 2026-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
