# Generated by Django 5.2.10 on 2026-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_tenantrequest_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='uid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
