# Generated by Django 5.2.10 on 2026-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_tenantrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
