# Generated by Django 5.2.10 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_tenantrequest_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantrequest",
            name="provisioned_domain",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tenantrequest",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tenantrequest",
            name="reset_uidb64",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]

