# Generated by Django 5.2.10 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0007_tenantrequest_provisioning_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantrequest",
            name="requested_plan_code",
            field=models.SlugField(blank=True, default="free"),
        ),
    ]

