# Generated by Django 5.2.10 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0008_tenantrequest_requested_plan_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantrequest",
            name="contact_first_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tenantrequest",
            name="contact_last_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]

