# Generated by Django 5.2.10 on 2026-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_tenantrequest_contact_first_last_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenantrequest',
            index=models.Index(fields=['status', 'created_at'], name='onboarding__status_d69cb6_idx'),
        ),
    ]
