# Generated by Django 5.2.10 on 2026-06-13 11:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0002_address_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=60)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Agent or firm reference number.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_agents', to='addresses.address')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='managing_ag_is_acti_9a497d_idx')],
            },
        ),
    ]
