# Generated by Django 5.2.10 on 2026-06-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managing_agents', '0003_managingagent_name'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='managingagent',
            new_name='managing_ag_is_acti_9a497d_idx',
            old_name='managing_a_is_acti_name_idx',
        ),
    ]
