# Generated by Django 5.2.10 on 2026-01-22 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10)),
                ('logger', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('pathname', models.CharField(blank=True, max_length=500)),
                ('lineno', models.IntegerField(blank=True, null=True)),
                ('func_name', models.CharField(blank=True, max_length=200)),
                ('module', models.CharField(blank=True, max_length=200)),
                ('process', models.IntegerField(blank=True, null=True)),
                ('thread', models.IntegerField(blank=True, null=True)),
                ('exc_text', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tenant_schema', models.CharField(blank=True, db_index=True, max_length=63)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=300)),
                ('actor_user_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor_email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='logs_logent_level_0f4f42_idx'), models.Index(fields=['logger', 'created_at'], name='logs_logent_logger_52ae10_idx'), models.Index(fields=['tenant_schema', 'created_at'], name='logs_logent_tenant__4619ab_idx'), models.Index(fields=['request_id'], name='logs_logent_request_9a9bf4_idx')],
            },
        ),
    ]
