# Generated by Django 5.2.10 on 2026-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='process',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='thread',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
