# Generated by Django 5.2.10 on 2026-01-22 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_logentry_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
