# Generated by Django 5.2.10 on 2026-01-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_logentry_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='logentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
