# Generated by Django 5.2.10 on 2026-01-25 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todo', '0002_alter_todoitem_content_type_alter_todoitem_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['status', 'created_at'], name='todo_todoit_status_f91685_idx'),
        ),
    ]
