# Generated by Django 5.2.10 on 2026-06-11 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		("addresses", "0002_address_tags"),
		("contacts", "0001_initial"),
	]

	operations = [
		migrations.CreateModel(
			name="Contractor",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("uid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
				("tags", models.JSONField(blank=True, default=list)),
				("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
				("updated_at", models.DateTimeField(auto_now=True)),
				("name", models.CharField(db_index=True, max_length=200)),
				("trade", models.CharField(blank=True, db_index=True, help_text="e.g. plumbing, electrical", max_length=120)),
				("email", models.EmailField(blank=True, db_index=True, max_length=254)),
				("phone", models.CharField(blank=True, db_index=True, max_length=60)),
				(
					"reference",
					models.CharField(
						blank=True,
						db_index=True,
						help_text="Contractor reference number.",
						max_length=120,
					),
				),
				("notes", models.TextField(blank=True)),
				("is_active", models.BooleanField(db_index=True, default=True)),
				(
					"address",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="contractors",
						to="addresses.address",
					),
				),
				(
					"contacts",
					models.ManyToManyField(
						blank=True,
						help_text="People linked to this contractor.",
						related_name="contractors",
						to="contacts.contact",
					),
				),
			],
			options={
				"ordering": ("name",),
				"indexes": [
					models.Index(fields=["is_active", "name"], name="contractors_is_acti_4a8f1d_idx"),
					models.Index(fields=["trade", "name"], name="contractors_trade_n_91c2e4_idx"),
				],
			},
		),
	]
