# Generated by Django 5.2.10 on 2026-06-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contractor',
            new_name='contractors_is_acti_fca617_idx',
            old_name='contractors_is_acti_4a8f1d_idx',
        ),
        migrations.RenameIndex(
            model_name='contractor',
            new_name='contractors_trade_405d70_idx',
            old_name='contractors_trade_n_91c2e4_idx',
        ),
    ]
