# Generated by Django 5.2.10 on 2026-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbranding',
            name='active_theme',
            field=models.CharField(db_index=True, default='theme1', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantbranding',
            name='themes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
